config/routes.rb
Rails.application.routes.draw do
  resources :coffee_shops  

  resources :projects
  resources :shared_projects
  resources :task_lists
  resources :tasks 
  resources :favorites
  resources :owners
  resources :assigned_tasks
  resources :assigned_owners
  resources :comments
  resources :smart_lists
  resources :sessions, only: [:new, :create, :destroy]

  root 'smart_lists#index'

  match '/signup', to: 'owners#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/assigned_owner.rb
class AssignedOwner < ActiveRecord::Base
	has_one :owner 
	belongs_to :task
end

app/models/assigned_task.rb
class AssignedTask < ActiveRecord::Base
	has_one :task 
	belongs_to :owner
end

app/models/coffee_shop.rb
class CoffeeShop < ActiveRecord::Base
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  validates :body, presence: true, length: { minimum: 1 }
  validates :commenter, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :owner
  has_many :tasks
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
 

  has_many :tasks
  has_one :favorite
  has_many :projects
  has_and_belongs_to_many :shared_projects
  has_many :assigned_tasks

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { minimum: 5 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { minimum: 1 }
  validates :password, length: { minimum: 6 }

  has_secure_password

  def Owner.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Owner.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
 
  private

    def create_remember_token
      self.remember_token = Owner.digest(Owner.new_remember_token)
    end

  end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :task_lists
	belongs_to :owner
    validates :name, presence: true, length: { minimum: 1 }
end

app/models/shared_project.rb
class SharedProject < ActiveRecord::Base
	has_many :task_lists
	has_and_belongs_to_many :owners
    validates :name, presence: true, length: { minimum: 1 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  has_many :comments
  has_one :assigned_owner
  validates :title, presence: true, length: { minimum: 1 }
  validates :status, presence: true
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :project
  has_many :tasks
  validates :name, presence: true, length: { minimum: 1 }
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  attr_accessor :name, :email
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
    @projects = @owner.projects.all
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        sign_in @owner
        flash[:success] = "Welcome to the SmartLists app!"
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  private

    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:task_id, :name, :email, :password, :password_confirmation, :favorite_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_list_id, :comments_id, :priority, :title, :owner_id, :due, :due_repeat, :reminder, :notes, :status, :location, :duration, :type, :timeframe, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_shops_helper.rb
module CoffeeShopsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = Owner.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, Owner.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = Owner.digest(cookies[:remember_token])
    @current_user ||= Owner.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  Owner.digest(Owner.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/smart_lists_helper.rb
module SmartListsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <%= render 'shared/error_messages' %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Create my account", class: "btn btn-large btn-primary"%>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<h1>Listing owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.email %></td>
        <td><%= owner.password %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<% provide(:title, @owner.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @owner.name %>
      </h1>
    </section>
  </aside>
</div>

<hr>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @owner.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @owner.password %>
</p>

<hr>

  <div class="span8">
    <% if @owner.projects.any? %>
      <h3>Projects (<%= @owner.projects.count %>)</h3>
      <ol class="projects">
        <%= render @projects %>
      </ol>
      <%= will_paginate @projects %>
    <% end %>
  </div>


<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_list_id %><br>
    <%= f.text_field :task_list_id %>
  </div>
  <div class="field">
    <%= f.label :comments_id %><br>
    <%= f.text_field :comments_id %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.text_field :due %>
  </div>
  <div class="field">
    <%= f.label :due_repeat %><br>
    <%= f.text_field :due_repeat %>
  </div>
  <div class="field">
    <%= f.label :reminder %><br>
    <%= f.text_field :reminder %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :timeframe %><br>
    <%= f.text_field :timeframe %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Task list</th>
      <th>Comments</th>
      <th>Priority</th>
      <th>Title</th>
      <th>Owner</th>
      <th>Due</th>
      <th>Due repeat</th>
      <th>Reminder</th>
      <th>Notes</th>
      <th>Status</th>
      <th>Location</th>
      <th>Duration</th>
      <th>Type</th>
      <th>Timeframe</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_list %></td>
        <td><%= task.comments %></td>
        <td><%= task.priority %></td>
        <td><%= task.title %></td>
        <td><%= task.owner %></td>
        <td><%= task.due %></td>
        <td><%= task.due_repeat %></td>
        <td><%= task.reminder %></td>
        <td><%= task.notes %></td>
        <td><%= task.status %></td>
        <td><%= task.location %></td>
        <td><%= task.duration %></td>
        <td><%= task.type %></td>
        <td><%= task.timeframe %></td>
        <td><%= task.category %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task list:</strong>
  <%= @task.task_list %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @task.comments %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @task.owner %>
</p>

<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>

<p>
  <strong>Due repeat:</strong>
  <%= @task.due_repeat %>
</p>

<p>
  <strong>Reminder:</strong>
  <%= @task.reminder %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @task.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Location:</strong>
  <%= @task.location %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Type:</strong>
  <%= @task.type %>
</p>

<p>
  <strong>Timeframe:</strong>
  <%= @task.timeframe %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task.category %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>