config/routes.rb
Rails.application.routes.draw do
  resources :coffee_shops  

  resources :projects
  resources :shared_projects
  resources :task_lists
  resources :tasks 
  resources :favorites
  resources :owners
  resources :assigned_tasks
  resources :assigned_owners
  resources :comments
  resources :smart_lists
  resources :sessions, only: [:new, :create, :destroy]

  root 'smart_lists#index'

  match '/signup', to: 'owners#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/assigned_owner.rb
class AssignedOwner < ActiveRecord::Base
	has_one :owner 
	belongs_to :task
end

app/models/assigned_task.rb
class AssignedTask < ActiveRecord::Base
	has_one :task 
	belongs_to :owner
end

app/models/coffee_shop.rb
class CoffeeShop < ActiveRecord::Base
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :task
  validates :body, presence: true, length: { minimum: 1 }
  validates :commenter, presence: true, length: { minimum: 1 }
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :owner
  has_many :tasks
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
 

  has_many :tasks
  has_one :favorite
  has_many :projects
  has_and_belongs_to_many :shared_projects
  has_many :assigned_tasks

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { minimum: 5 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { minimum: 1 }
  validates :password, length: { minimum: 6 }

  has_secure_password

  def Owner.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Owner.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
 
  private

    def create_remember_token
      self.remember_token = Owner.digest(Owner.new_remember_token)
    end

  end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :task_lists
	belongs_to :owner
    validates :name, presence: true, length: { minimum: 1 }
end

app/models/shared_project.rb
class SharedProject < ActiveRecord::Base
	has_many :task_lists
	has_and_belongs_to_many :owners
    validates :name, presence: true, length: { minimum: 1 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_list
  has_many :comments
  has_one :assigned_owner
  validates :title, presence: true, length: { minimum: 1 }
  validates :status, presence: true
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  belongs_to :project
  has_many :tasks
  validates :name, presence: true, length: { minimum: 1 }
end

app/controllers/assigned_tasks_controller.rb
class AssignedTasksController < ApplicationController
  before_action :set_assigned_task, only: [:show, :edit, :update, :destroy]

  # GET /assigned_tasks
  # GET /assigned_tasks.json
  def index
    @assigned_tasks = AssignedTask.all
  end

  # GET /assigned_tasks/1
  # GET /assigned_tasks/1.json
  def show
  end

  # GET /assigned_tasks/new
  def new
    @assigned_task = AssignedTask.new
  end

  # GET /assigned_tasks/1/edit
  def edit
  end

  # POST /assigned_tasks
  # POST /assigned_tasks.json
  def create
    @assigned_task = AssignedTask.new(assigned_task_params)

    respond_to do |format|
      if @assigned_task.save
        format.html { redirect_to @assigned_task, notice: 'Assigned task was successfully created.' }
        format.json { render :show, status: :created, location: @assigned_task }
      else
        format.html { render :new }
        format.json { render json: @assigned_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assigned_tasks/1
  # PATCH/PUT /assigned_tasks/1.json
  def update
    respond_to do |format|
      if @assigned_task.update(assigned_task_params)
        format.html { redirect_to @assigned_task, notice: 'Assigned task was successfully updated.' }
        format.json { render :show, status: :ok, location: @assigned_task }
      else
        format.html { render :edit }
        format.json { render json: @assigned_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assigned_tasks/1
  # DELETE /assigned_tasks/1.json
  def destroy
    @assigned_task.destroy
    respond_to do |format|
      format.html { redirect_to assigned_tasks_url, notice: 'Assigned task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assigned_task
      @assigned_task = AssignedTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assigned_task_params
      params.require(:assigned_task).permit(:task_id, :owner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assigned_tasks_helper.rb
module AssignedTasksHelper
end

app/helpers/coffee_shops_helper.rb
module CoffeeShopsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = Owner.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, Owner.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = Owner.digest(cookies[:remember_token])
    @current_user ||= Owner.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  Owner.digest(Owner.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

end

app/helpers/smart_lists_helper.rb
module SmartListsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/assigned_tasks/_form.html.erb
<%= form_for(@assigned_task) do |f| %>
  <% if @assigned_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assigned_task.errors.count, "error") %> prohibited this assigned_task from being saved:</h2>

      <ul>
      <% @assigned_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.text_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assigned_tasks/edit.html.erb
<h1>Editing assigned_task</h1>

<%= render 'form' %>

<%= link_to 'Show', @assigned_task %> |
<%= link_to 'Back', assigned_tasks_path %>

app/views/assigned_tasks/index.html.erb
<h1>Listing assigned_tasks</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assigned_tasks.each do |assigned_task| %>
      <tr>
        <td><%= assigned_task.task %></td>
        <td><%= assigned_task.owner %></td>
        <td><%= link_to 'Show', assigned_task %></td>
        <td><%= link_to 'Edit', edit_assigned_task_path(assigned_task) %></td>
        <td><%= link_to 'Destroy', assigned_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assigned task', new_assigned_task_path %>

app/views/assigned_tasks/new.html.erb
<h1>New assigned_task</h1>

<%= render 'form' %>

<%= link_to 'Back', assigned_tasks_path %>

app/views/assigned_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @assigned_task.task %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @assigned_task.owner %>
</p>

<%= link_to 'Edit', edit_assigned_task_path(@assigned_task) %> |
<%= link_to 'Back', assigned_tasks_path %>